variables:
  - group: ADO-TF-AWS-VPC-Int
  - name: region
    value: 'us-east-2'
  
trigger:
  branches:
    include:
    - main
  
stages:
  - stage: Validate
    displayName: Validate
    jobs:
    - job: validate
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
        inputs:
          terraformVersion: '0.14.8'
      
      
      
      
      
      
      