variables:
  - group: ADO-TF-AWS-VPC-Int
  - name: region
    value: 'us-east-2'
  
trigger:
  branches:
    include:
    - add-build
  
stages:
  - stage: Validate
    displayName: Validate
    jobs:
    - job: validate
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: TerraformInstaller@0
        displayName: Install Terraform
        inputs:
          terraformVersion: '0.14.8'

      # Init
      - powershell: |
        terraform init -backend-config="bucket=terraform-project4" -backend-config="key=tf/terraform.tfstate" -backend-config="region=$(region)" -backend-config="access_key=$(access_key)" -backend-config="secret_key=$(secret_key)" -no-color
          workingDirectory:'$(build.sourcesdirectory)'
          displayName:'terraform init'